/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedDashboardPreviewRouteImport } from './routes/_authenticated.dashboard-preview'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated.dashboard.settings'
import { Route as AuthenticatedDashboardScansRouteImport } from './routes/_authenticated.dashboard.scans'
import { Route as AuthenticatedDashboardPromptsRouteImport } from './routes/_authenticated.dashboard.prompts'
import { Route as AuthenticatedDashboardPixelRouteImport } from './routes/_authenticated.dashboard.pixel'
import { Route as AuthenticatedDashboardContentAnalysisRouteImport } from './routes/_authenticated.dashboard.content-analysis'
import { Route as AuthenticatedDashboardCompetitorsRouteImport } from './routes/_authenticated.dashboard.competitors'
import { Route as AuthenticatedDashboardCitationsRouteImport } from './routes/_authenticated.dashboard.citations'
import { Route as AuthenticatedDashboardBrandsRouteImport } from './routes/_authenticated.dashboard.brands'
import { Route as AuthenticatedDashboardActionsRouteImport } from './routes/_authenticated.dashboard.actions'

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardPreviewRoute =
  AuthenticatedDashboardPreviewRouteImport.update({
    id: '/dashboard-preview',
    path: '/dashboard-preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardScansRoute =
  AuthenticatedDashboardScansRouteImport.update({
    id: '/scans',
    path: '/scans',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPromptsRoute =
  AuthenticatedDashboardPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPixelRoute =
  AuthenticatedDashboardPixelRouteImport.update({
    id: '/pixel',
    path: '/pixel',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContentAnalysisRoute =
  AuthenticatedDashboardContentAnalysisRouteImport.update({
    id: '/content-analysis',
    path: '/content-analysis',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCompetitorsRoute =
  AuthenticatedDashboardCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCitationsRoute =
  AuthenticatedDashboardCitationsRouteImport.update({
    id: '/citations',
    path: '/citations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBrandsRoute =
  AuthenticatedDashboardBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardActionsRoute =
  AuthenticatedDashboardActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard-preview': typeof AuthenticatedDashboardPreviewRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/actions': typeof AuthenticatedDashboardActionsRoute
  '/dashboard/brands': typeof AuthenticatedDashboardBrandsRoute
  '/dashboard/citations': typeof AuthenticatedDashboardCitationsRoute
  '/dashboard/competitors': typeof AuthenticatedDashboardCompetitorsRoute
  '/dashboard/content-analysis': typeof AuthenticatedDashboardContentAnalysisRoute
  '/dashboard/pixel': typeof AuthenticatedDashboardPixelRoute
  '/dashboard/prompts': typeof AuthenticatedDashboardPromptsRoute
  '/dashboard/scans': typeof AuthenticatedDashboardScansRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/dashboard-preview': typeof AuthenticatedDashboardPreviewRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/actions': typeof AuthenticatedDashboardActionsRoute
  '/dashboard/brands': typeof AuthenticatedDashboardBrandsRoute
  '/dashboard/citations': typeof AuthenticatedDashboardCitationsRoute
  '/dashboard/competitors': typeof AuthenticatedDashboardCompetitorsRoute
  '/dashboard/content-analysis': typeof AuthenticatedDashboardContentAnalysisRoute
  '/dashboard/pixel': typeof AuthenticatedDashboardPixelRoute
  '/dashboard/prompts': typeof AuthenticatedDashboardPromptsRoute
  '/dashboard/scans': typeof AuthenticatedDashboardScansRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard-preview': typeof AuthenticatedDashboardPreviewRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authenticated/dashboard/actions': typeof AuthenticatedDashboardActionsRoute
  '/_authenticated/dashboard/brands': typeof AuthenticatedDashboardBrandsRoute
  '/_authenticated/dashboard/citations': typeof AuthenticatedDashboardCitationsRoute
  '/_authenticated/dashboard/competitors': typeof AuthenticatedDashboardCompetitorsRoute
  '/_authenticated/dashboard/content-analysis': typeof AuthenticatedDashboardContentAnalysisRoute
  '/_authenticated/dashboard/pixel': typeof AuthenticatedDashboardPixelRoute
  '/_authenticated/dashboard/prompts': typeof AuthenticatedDashboardPromptsRoute
  '/_authenticated/dashboard/scans': typeof AuthenticatedDashboardScansRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/dashboard'
    | '/dashboard-preview'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/actions'
    | '/dashboard/brands'
    | '/dashboard/citations'
    | '/dashboard/competitors'
    | '/dashboard/content-analysis'
    | '/dashboard/pixel'
    | '/dashboard/prompts'
    | '/dashboard/scans'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/dashboard-preview'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/actions'
    | '/dashboard/brands'
    | '/dashboard/citations'
    | '/dashboard/competitors'
    | '/dashboard/content-analysis'
    | '/dashboard/pixel'
    | '/dashboard/prompts'
    | '/dashboard/scans'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard-preview'
    | '/_authenticated/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authenticated/dashboard/actions'
    | '/_authenticated/dashboard/brands'
    | '/_authenticated/dashboard/citations'
    | '/_authenticated/dashboard/competitors'
    | '/_authenticated/dashboard/content-analysis'
    | '/_authenticated/dashboard/pixel'
    | '/_authenticated/dashboard/prompts'
    | '/_authenticated/dashboard/scans'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard-preview': {
      id: '/_authenticated/dashboard-preview'
      path: '/dashboard-preview'
      fullPath: '/dashboard-preview'
      preLoaderRoute: typeof AuthenticatedDashboardPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/scans': {
      id: '/_authenticated/dashboard/scans'
      path: '/scans'
      fullPath: '/dashboard/scans'
      preLoaderRoute: typeof AuthenticatedDashboardScansRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/prompts': {
      id: '/_authenticated/dashboard/prompts'
      path: '/prompts'
      fullPath: '/dashboard/prompts'
      preLoaderRoute: typeof AuthenticatedDashboardPromptsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pixel': {
      id: '/_authenticated/dashboard/pixel'
      path: '/pixel'
      fullPath: '/dashboard/pixel'
      preLoaderRoute: typeof AuthenticatedDashboardPixelRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/content-analysis': {
      id: '/_authenticated/dashboard/content-analysis'
      path: '/content-analysis'
      fullPath: '/dashboard/content-analysis'
      preLoaderRoute: typeof AuthenticatedDashboardContentAnalysisRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/competitors': {
      id: '/_authenticated/dashboard/competitors'
      path: '/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof AuthenticatedDashboardCompetitorsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/citations': {
      id: '/_authenticated/dashboard/citations'
      path: '/citations'
      fullPath: '/dashboard/citations'
      preLoaderRoute: typeof AuthenticatedDashboardCitationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/brands': {
      id: '/_authenticated/dashboard/brands'
      path: '/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof AuthenticatedDashboardBrandsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/actions': {
      id: '/_authenticated/dashboard/actions'
      path: '/actions'
      fullPath: '/dashboard/actions'
      preLoaderRoute: typeof AuthenticatedDashboardActionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardActionsRoute: typeof AuthenticatedDashboardActionsRoute
  AuthenticatedDashboardBrandsRoute: typeof AuthenticatedDashboardBrandsRoute
  AuthenticatedDashboardCitationsRoute: typeof AuthenticatedDashboardCitationsRoute
  AuthenticatedDashboardCompetitorsRoute: typeof AuthenticatedDashboardCompetitorsRoute
  AuthenticatedDashboardContentAnalysisRoute: typeof AuthenticatedDashboardContentAnalysisRoute
  AuthenticatedDashboardPixelRoute: typeof AuthenticatedDashboardPixelRoute
  AuthenticatedDashboardPromptsRoute: typeof AuthenticatedDashboardPromptsRoute
  AuthenticatedDashboardScansRoute: typeof AuthenticatedDashboardScansRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardActionsRoute: AuthenticatedDashboardActionsRoute,
    AuthenticatedDashboardBrandsRoute: AuthenticatedDashboardBrandsRoute,
    AuthenticatedDashboardCitationsRoute: AuthenticatedDashboardCitationsRoute,
    AuthenticatedDashboardCompetitorsRoute:
      AuthenticatedDashboardCompetitorsRoute,
    AuthenticatedDashboardContentAnalysisRoute:
      AuthenticatedDashboardContentAnalysisRoute,
    AuthenticatedDashboardPixelRoute: AuthenticatedDashboardPixelRoute,
    AuthenticatedDashboardPromptsRoute: AuthenticatedDashboardPromptsRoute,
    AuthenticatedDashboardScansRoute: AuthenticatedDashboardScansRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDashboardPreviewRoute: typeof AuthenticatedDashboardPreviewRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDashboardPreviewRoute: AuthenticatedDashboardPreviewRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
